In [ ]:
import pandas as pd
import os

path = "/content/customer_360"

customers = pd.read_csv(f"{path}/customers.csv")
orders = pd.read_csv(f"{path}/orders.csv")
products = pd.read_csv(f"{path}/products.csv")
support = pd.read_csv(f"{path}/support_tickets.csv")
clickstream = pd.read_csv(f"{path}/clickstream.csv")

## Data Loading and Initial Inspection

In [ ]:
print(customers.shape)
print(customers.columns)

(3, 5)
Index(['customer_id', 'name', 'email', 'age', 'gender'], dtype='object')

In [ ]:
customers.dtypes

customer_id     int64
name           object
email          object
age             int64
gender         object
dtype: object

In [ ]:
customers.isnull().sum()

customer_id    0
name           0
email          0
age            0
gender         0
dtype: int64

In [ ]:
(customers.isnull().sum() / len(customers) * 100).sort_values(
    ascending=False
)

customer_id    0.0
name           0.0
email          0.0
age            0.0
gender         0.0
dtype: float64

In [ ]:
customers.duplicated().sum()

np.int64(0)

In [ ]:
customers.nunique()

customer_id    3
name           3
email          3
age            3
gender         2
dtype: int64

In [ ]:
customers.describe()

       customer_id        age
count          3.0   3.000000
mean           2.0  29.666667
std            1.0   5.507571
min            1.0  24.000000
25%            1.5  27.000000
50%            2.0  30.000000
75%            2.5  32.500000
max            3.0  35.000000

In [ ]:
customers.describe(include="object")

         name              email gender
count       3                  3      3
unique      3                  3      2
top     Alice  alice@example.com      M
freq        1                  1      2

In [ ]:
def profile_dataset(df, name):

    print("=" * 70)
    print("DATASET:", name)
    print("=" * 70)

    print("\nShape:")
    print(df.shape)

    print("\nColumns:")
    print(df.columns.tolist())

    print("\nData Types:")
    print(df.dtypes)

    print("\nMissing Values:")
    print(df.isnull().sum())

    print("\nMissing Percentage:")
    print((df.isnull().sum() / len(df) * 100).round(2))

    print("\nDuplicate Rows:")
    print(df.duplicated().sum())

    print("\nUnique Values:")
    print(df.nunique())

    print("\nStatistical Summary:")
    print(df.describe(include="all"))

In [ ]:
profile_dataset(customers, "Customers")
profile_dataset(orders, "Orders")
profile_dataset(products, "Products")
profile_dataset(support, "Support Tickets")
profile_dataset(clickstream, "Clickstream")

======================================================================
DATASET: Customers
======================================================================

Shape:
(3, 5)

Columns:
['customer_id', 'name', 'email', 'age', 'gender']

Data Types:
customer_id     int64
name           object
email          object
age             int64
gender         object
dtype: object

Missing Values:
customer_id    0
name           0
email          0
age            0
gender         0
dtype: int64

Missing Percentage:
customer_id    0.0
name           0.0
email          0.0
age            0.0
gender         0.0
dtype: float64

Duplicate Rows:
0

Unique Values:
customer_id    3
name           3
email          3
age            3
gender         2
dtype: int64

Statistical Summary:
        customer_id   name              email        age gender
count           3.0      3                  3   3.000000      3
unique          NaN      3                  3        NaN      2
top             NaN  Alice  alice@example.com        NaN      M
freq            NaN      1                  1        NaN      2
mean            2.0    NaN                NaN  29.666667    NaN
std             1.0    NaN                NaN   5.507571    NaN
min             1.0    NaN                NaN  24.000000    NaN
25%             1.5    NaN                NaN  27.000000    NaN
50%             2.0    NaN                NaN  30.000000    NaN
75%             2.5    NaN                NaN  32.500000    NaN
max             3.0    NaN                NaN  35.000000    NaN
======================================================================
DATASET: Orders
======================================================================

Shape:
(4, 6)

Columns:
['order_id', 'customer_id', 'product_id', 'order_date', 'quantity', 'price']

Data Types:
order_id         int64
customer_id      int64
product_id       int64
order_date      object
quantity         int64
price          float64
dtype: object

Missing Values:
order_id       0
customer_id    0
product_id     0
order_date     0
quantity       0
price          0
dtype: int64

Missing Percentage:
order_id       0.0
customer_id    0.0
product_id     0.0
order_date     0.0
quantity       0.0
price          0.0
dtype: float64

Duplicate Rows:
0

Unique Values:
order_id       4
customer_id    3
product_id     3
order_date     4
quantity       2
price          3
dtype: int64

Statistical Summary:
          order_id  customer_id   product_id  order_date  quantity       price
count     4.000000     4.000000     4.000000           4      4.00    4.000000
unique         NaN          NaN          NaN           4       NaN         NaN
top            NaN          NaN          NaN  2023-01-01       NaN         NaN
freq           NaN          NaN          NaN           1       NaN         NaN
mean    102.500000     1.750000  1001.750000         NaN      1.25   67.500000
std       1.290994     0.957427     0.957427         NaN      0.50   56.789083
min     101.000000     1.000000  1001.000000         NaN      1.00   20.000000
25%     101.750000     1.000000  1001.000000         NaN      1.00   42.500000
50%     102.500000     1.500000  1001.500000         NaN      1.00   50.000000
75%     103.250000     2.250000  1002.250000         NaN      1.25   75.000000
max     104.000000     3.000000  1003.000000         NaN      2.00  150.000000
======================================================================
DATASET: Products
======================================================================

Shape:
(3, 4)

Columns:
['product_id', 'name', 'category', 'price']

Data Types:
product_id      int64
name           object
category       object
price         float64
dtype: object

Missing Values:
product_id    0
name          0
category      0
price         0
dtype: int64

Missing Percentage:
product_id    0.0
name          0.0
category      0.0
price         0.0
dtype: float64

Duplicate Rows:
0

Unique Values:
product_id    3
name          3
category      3
price         3
dtype: int64

Statistical Summary:
        product_id       name     category       price
count          3.0          3            3    3.000000
unique         NaN          3            3         NaN
top            NaN  Product A  Electronics         NaN
freq           NaN          1            1         NaN
mean        1002.0        NaN          NaN   73.333333
std            1.0        NaN          NaN   68.068593
min         1001.0        NaN          NaN   20.000000
25%         1001.5        NaN          NaN   35.000000
50%         1002.0        NaN          NaN   50.000000
75%         1002.5        NaN          NaN  100.000000
max         1003.0        NaN          NaN  150.000000
======================================================================
DATASET: Support Tickets
======================================================================

Shape:
(2, 4)

Columns:
['ticket_id', 'customer_id', 'issue', 'status']

Data Types:
ticket_id       int64
customer_id     int64
issue          object
status         object
dtype: object

Missing Values:
ticket_id      0
customer_id    0
issue          0
status         0
dtype: int64

Missing Percentage:
ticket_id      0.0
customer_id    0.0
issue          0.0
status         0.0
dtype: float64

Duplicate Rows:
0

Unique Values:
ticket_id      2
customer_id    2
issue          2
status         2
dtype: int64

Statistical Summary:
         ticket_id  customer_id          issue status
count     2.000000     2.000000              2      2
unique         NaN          NaN              2      2
top            NaN          NaN  Login problem   Open
freq           NaN          NaN              1      1
mean    201.500000     1.500000            NaN    NaN
std       0.707107     0.707107            NaN    NaN
min     201.000000     1.000000            NaN    NaN
25%     201.250000     1.250000            NaN    NaN
50%     201.500000     1.500000            NaN    NaN
75%     201.750000     1.750000            NaN    NaN
max     202.000000     2.000000            NaN    NaN
======================================================================
DATASET: Clickstream
======================================================================

Shape:
(4, 4)

Columns:
['session_id', 'customer_id', 'timestamp', 'page_visited']

Data Types:
session_id       int64
customer_id      int64
timestamp       object
page_visited    object
dtype: object

Missing Values:
session_id      0
customer_id     0
timestamp       0
page_visited    0
dtype: int64

Missing Percentage:
session_id      0.0
customer_id     0.0
timestamp       0.0
page_visited    0.0
dtype: float64

Duplicate Rows:
0

Unique Values:
session_id      3
customer_id     3
timestamp       4
page_visited    3
dtype: int64

Statistical Summary:
        session_id  customer_id            timestamp page_visited
count     4.000000     4.000000                    4            4
unique         NaN          NaN                    4            3
top            NaN          NaN  2023-01-01 10:00:00     homepage
freq           NaN          NaN                    1            2
mean    301.750000     1.750000                  NaN          NaN
std       0.957427     0.957427                  NaN          NaN
min     301.000000     1.000000                  NaN          NaN
25%     301.000000     1.000000                  NaN          NaN
50%     301.500000     1.500000                  NaN          NaN
75%     302.250000     2.250000                  NaN          NaN
max     303.000000     3.000000                  NaN          NaN

In [ ]:
profile_dataset(customers, "Customers")
profile_dataset(orders, "Orders")
profile_dataset(products, "Products")
profile_dataset(support, "Support Tickets")
profile_dataset(clickstream, "Clickstream")

======================================================================
DATASET: Customers
======================================================================

Shape:
(3, 5)

Columns:
['customer_id', 'name', 'email', 'age', 'gender']

Data Types:
customer_id     int64
name           object
email          object
age             int64
gender         object
dtype: object

Missing Values:
customer_id    0
name           0
email          0
age            0
gender         0
dtype: int64

Missing Percentage:
customer_id    0.0
name           0.0
email          0.0
age            0.0
gender         0.0
dtype: float64

Duplicate Rows:
0

Unique Values:
customer_id    3
name           3
email          3
age            3
gender         2
dtype: int64

Statistical Summary:
        customer_id   name              email        age gender
count           3.0      3                  3   3.000000      3
unique          NaN      3                  3        NaN      2
top             NaN  Alice  alice@example.com        NaN      M
freq            NaN      1                  1        NaN      2
mean            2.0    NaN                NaN  29.666667    NaN
std             1.0    NaN                NaN   5.507571    NaN
min             1.0    NaN                NaN  24.000000    NaN
25%             1.5    NaN                NaN  27.000000    NaN
50%             2.0    NaN                NaN  30.000000    NaN
75%             2.5    NaN                NaN  32.500000    NaN
max             3.0    NaN                NaN  35.000000    NaN
======================================================================
DATASET: Orders
======================================================================

Shape:
(4, 6)

Columns:
['order_id', 'customer_id', 'product_id', 'order_date', 'quantity', 'price']

Data Types:
order_id         int64
customer_id      int64
product_id       int64
order_date      object
quantity         int64
price          float64
dtype: object

Missing Values:
order_id       0
customer_id    0
product_id     0
order_date     0
quantity       0
price          0
dtype: int64

Missing Percentage:
order_id       0.0
customer_id    0.0
product_id     0.0
order_date     0.0
quantity       0.0
price          0.0
dtype: float64

Duplicate Rows:
0

Unique Values:
order_id       4
customer_id    3
product_id     3
order_date     4
quantity       2
price          3
dtype: int64

Statistical Summary:
          order_id  customer_id   product_id  order_date  quantity       price
count     4.000000     4.000000     4.000000           4      4.00    4.000000
unique         NaN          NaN          NaN           4       NaN         NaN
top            NaN          NaN          NaN  2023-01-01       NaN         NaN
freq           NaN          NaN          NaN           1       NaN         NaN
mean    102.500000     1.750000  1001.750000         NaN      1.25   67.500000
std       1.290994     0.957427     0.957427         NaN      0.50   56.789083
min     101.000000     1.000000  1001.000000         NaN      1.00   20.000000
25%     101.750000     1.000000  1001.000000         NaN      1.00   42.500000
50%     102.500000     1.500000  1001.500000         NaN      1.00   50.000000
75%     103.250000     2.250000  1002.250000         NaN      1.25   75.000000
max     104.000000     3.000000  1003.000000         NaN      2.00  150.000000
======================================================================
DATASET: Products
======================================================================

Shape:
(3, 4)

Columns:
['product_id', 'name', 'category', 'price']

Data Types:
product_id      int64
name           object
category       object
price         float64
dtype: object

Missing Values:
product_id    0
name          0
category      0
price         0
dtype: int64

Missing Percentage:
product_id    0.0
name          0.0
category      0.0
price         0.0
dtype: float64

Duplicate Rows:
0

Unique Values:
product_id    3
name          3
category      3
price         3
dtype: int64

Statistical Summary:
        product_id       name     category       price
count          3.0          3            3    3.000000
unique         NaN          3            3         NaN
top            NaN  Product A  Electronics         NaN
freq           NaN          1            1         NaN
mean        1002.0        NaN          NaN   73.333333
std            1.0        NaN          NaN   68.068593
min         1001.0        NaN          NaN   20.000000
25%         1001.5        NaN          NaN   35.000000
50%         1002.0        NaN          NaN   50.000000
75%         1002.5        NaN          NaN  100.000000
max         1003.0        NaN          NaN  150.000000
======================================================================
DATASET: Support Tickets
======================================================================

Shape:
(2, 4)

Columns:
['ticket_id', 'customer_id', 'issue', 'status']

Data Types:
ticket_id       int64
customer_id     int64
issue          object
status         object
dtype: object

Missing Values:
ticket_id      0
customer_id    0
issue          0
status         0
dtype: int64

Missing Percentage:
ticket_id      0.0
customer_id    0.0
issue          0.0
status         0.0
dtype: float64

Duplicate Rows:
0

Unique Values:
ticket_id      2
customer_id    2
issue          2
status         2
dtype: int64

Statistical Summary:
         ticket_id  customer_id          issue status
count     2.000000     2.000000              2      2
unique         NaN          NaN              2      2
top            NaN          NaN  Login problem   Open
freq           NaN          NaN              1      1
mean    201.500000     1.500000            NaN    NaN
std       0.707107     0.707107            NaN    NaN
min     201.000000     1.000000            NaN    NaN
25%     201.250000     1.250000            NaN    NaN
50%     201.500000     1.500000            NaN    NaN
75%     201.750000     1.750000            NaN    NaN
max     202.000000     2.000000            NaN    NaN
======================================================================
DATASET: Clickstream
======================================================================

Shape:
(4, 4)

Columns:
['session_id', 'customer_id', 'timestamp', 'page_visited']

Data Types:
session_id       int64
customer_id      int64
timestamp       object
page_visited    object
dtype: object

Missing Values:
session_id      0
customer_id     0
timestamp       0
page_visited    0
dtype: int64

Missing Percentage:
session_id      0.0
customer_id     0.0
timestamp       0.0
page_visited    0.0
dtype: float64

Duplicate Rows:
0

Unique Values:
session_id      3
customer_id     3
timestamp       4
page_visited    3
dtype: int64

Statistical Summary:
        session_id  customer_id            timestamp page_visited
count     4.000000     4.000000                    4            4
unique         NaN          NaN                    4            3
top            NaN          NaN  2023-01-01 10:00:00     homepage
freq           NaN          NaN                    1            2
mean    301.750000     1.750000                  NaN          NaN
std       0.957427     0.957427                  NaN          NaN
min     301.000000     1.000000                  NaN          NaN
25%     301.000000     1.000000                  NaN          NaN
50%     301.500000     1.500000                  NaN          NaN
75%     302.250000     2.250000                  NaN          NaN
max     303.000000     3.000000                  NaN          NaN

### Standardize Column Names

## Data Preprocessing and Cleaning

In [ ]:
customers.columns = customers.columns.str.lower().str.strip()

### Handle Duplicates

In [ ]:
customers = customers.drop_duplicates()

### Clean Text Data

In [ ]:
customers["name"] = customers["name"].str.strip()

### Convert Data Types

In [ ]:
orders["order_date"] = pd.to_datetime(
    orders["order_date"],
    errors="coerce"
)

In [ ]:
orders["quantity"] = pd.to_numeric(
    orders["quantity"],
    errors="coerce"
)

### Derive New Features

In [ ]:
orders["total_amount"] = (
    orders["quantity"] * orders["price"]
)

## Data Integration

In [ ]:
customer_orders = customers.merge(
    orders,
    on="customer_id",
    how="left"
)

## STEP 1 — Review Integrated Data

I will now inspect the `customer_orders` DataFrame, which is the result of merging customer and order data. This inspection will cover its shape, columns, data types, missing values, duplicate records, and statistical summaries.

In [ ]:
profile_dataset(customer_orders, "Customer Orders")

======================================================================
DATASET: Customer Orders
======================================================================

Shape:
(4, 11)

Columns:
['customer_id', 'name', 'email', 'age', 'gender', 'order_id', 'product_id', 'order_date', 'quantity', 'price', 'total_amount']

Data Types:
customer_id              int64
name                    object
email                   object
age                      int64
gender                  object
order_id                 int64
product_id               int64
order_date      datetime64[ns]
quantity                 int64
price                  float64
total_amount           float64
dtype: object

Missing Values:
customer_id     0
name            0
email           0
age             0
gender          0
order_id        0
product_id      0
order_date      0
quantity        0
price           0
total_amount    0
dtype: int64

Missing Percentage:
customer_id     0.0
name            0.0
email           0.0
age             0.0
gender          0.0
order_id        0.0
product_id      0.0
order_date      0.0
quantity        0.0
price           0.0
total_amount    0.0
dtype: float64

Duplicate Rows:
0

Unique Values:
customer_id     3
name            3
email           3
age             3
gender          2
order_id        4
product_id      3
order_date      4
quantity        2
price           3
total_amount    3
dtype: int64

Statistical Summary:
        customer_id   name              email    age gender    order_id  \
count      4.000000      4                  4   4.00      4    4.000000
unique          NaN      3                  3    NaN      2         NaN
top             NaN  Alice  alice@example.com    NaN      F         NaN
freq            NaN      2                  2    NaN      2         NaN
mean       1.750000    NaN                NaN  29.75    NaN  102.500000
min        1.000000    NaN                NaN  24.00    NaN  101.000000
25%        1.000000    NaN                NaN  28.50    NaN  101.750000
50%        1.500000    NaN                NaN  30.00    NaN  102.500000
75%        2.250000    NaN                NaN  31.25    NaN  103.250000
max        3.000000    NaN                NaN  35.00    NaN  104.000000
std        0.957427    NaN                NaN   4.50    NaN    1.290994

         product_id           order_date  quantity       price  total_amount
count      4.000000                    4      4.00    4.000000      4.000000
unique          NaN                  NaN       NaN         NaN           NaN
top             NaN                  NaN       NaN         NaN           NaN
freq            NaN                  NaN       NaN         NaN           NaN
mean    1001.750000  2023-01-04 12:00:00      1.25   67.500000     72.500000
min     1001.000000  2023-01-01 00:00:00      1.00   20.000000     40.000000
25%     1001.000000  2023-01-01 18:00:00      1.00   42.500000     47.500000
50%     1001.500000  2023-01-03 12:00:00      1.00   50.000000     50.000000
75%     1002.250000  2023-01-06 06:00:00      1.25   75.000000     75.000000
max     1003.000000  2023-01-10 00:00:00      2.00  150.000000    150.000000
std        0.957427                  NaN      0.50   56.789083     51.881275

### Validation Report for `customer_orders`

Based on the profiling of the `customer_orders` DataFrame, here's a concise validation report:

*   **Shape:** (4 rows, 11 columns). The merge operation successfully combined customer information with their respective orders. Each row represents an order transaction with associated customer details.
*   **Columns:**
    *   `customer_id` (int64): Identifier for customers. No missing values, 3 unique customers, correctly merged.
    *   `name` (object): Customer name. No missing values.
    *   `email` (object): Customer email. No missing values.
    *   `age` (int64): Customer age. No missing values.
    *   `gender` (object): Customer gender. No missing values.
    *   `order_id` (int64): Unique identifier for each order. No missing values, 4 unique orders.
    *   `product_id` (int64): Identifier for products. No missing values.
    *   `order_date` (datetime64[ns]): Date of the order. No missing values, correctly converted to datetime.
    *   `quantity` (int64): Quantity of products in an order. No missing values.
    *   `price` (float64): Unit price of the product at the time of order. No missing values.
    *   `total_amount` (float64): Calculated total amount for the order (quantity * price). No missing values.
*   **Data Types:** All columns have appropriate data types, with `order_date` correctly converted to datetime format and numeric fields as integers or floats.
*   **Missing Values:** There are no missing values across all columns, indicating a clean merge and complete records for the integrated data.
*   **Duplicate Records:** No duplicate rows were found in the `customer_orders` DataFrame, indicating data integrity post-merge.
*   **Primary/Business Keys:** `customer_id` acts as a business key for customer details, and `order_id` for order details. They maintain their uniqueness and integrity after the merge.
*   **Relationships:** The merge was performed on `customer_id`, successfully linking customer details to their orders. This establishes a one-to-many relationship where one customer can have multiple orders.
*   **Referential Integrity:** Given the 'left' merge, all `customer_id` values from the `customers` table are present, and their corresponding order details are included where available. No `customer_id` in `orders` was orphaned.
*   **Unexpected Values:** No immediate unexpected values were identified from the statistical summaries for numerical columns (`age`, `quantity`, `price`, `total_amount`). Categorical columns (`gender`, `name`, `email`) appear consistent with expected values for dummy data.

## STEP 2 — Design a Data Warehouse

Based on the Customer 360 data, we will design a **Star Schema**. This model separates business process data (measures) into fact tables and descriptive attributes into dimension tables, optimizing for query performance and ease of understanding.

### Star Schema Design

**Fact Tables** will store quantitative data about business events, linked by foreign keys to dimensions. **Dimension Tables** will store qualitative, descriptive data, providing context to the facts.

### Dimension Tables

Dimension tables provide descriptive context for the numerical facts. They are typically denormalized for query performance.

1.  **`dim_customer`**
    *   **Purpose:** Stores static and demographic information about each customer.
    *   **Justification:** Essential for analyzing customer behavior, segmenting customers by age, gender, or other attributes, and understanding customer demographics in relation to sales, support, and clickstream data.
    *   **Business Key:** `customer_id`
    *   **Proposed Columns:** `customer_key` (Surrogate Key), `customer_id` (Business Key), `name` (customer name), `email`, `age`, `gender`.

2.  **`dim_product`**
    *   **Purpose:** Contains descriptive attributes for each product.
    *   **Justification:** Enables analysis of sales performance, customer preferences, and support issues based on product categories, names, or other product-specific details.
    *   **Business Key:** `product_id`
    *   **Proposed Columns:** `product_key` (Surrogate Key), `product_id` (Business Key), `name` (product name), `category`.

3.  **`dim_date`**
    *   **Purpose:** Provides a rich set of date-related attributes for time-based analysis.
    *   **Justification:** Critical for analyzing trends, seasonality, and time-specific patterns across orders, support tickets, and clickstream events. It centralizes all date information.
    *   **Business Keys:** Derived from `order_date` (from `orders`) and `timestamp` (from `clickstream`).
    *   **Proposed Columns:** `date_key` (Surrogate Key, e.g., YYYYMMDD), `full_date`, `day`, `day_name`, `week`, `month`, `month_name`, `quarter`, `year`.

4.  **`dim_support_status`**
    *   **Purpose:** Stores distinct statuses for support tickets.
    *   **Justification:** Allows for standardized reporting and analysis of ticket resolution workflows, common statuses, and the efficiency of the support process.
    *   **Business Key:** `status`
    *   **Proposed Columns:** `support_status_key` (Surrogate Key), `status` (e.g., 'Open', 'Closed').

5.  **`dim_page`**
    *   **Purpose:** Stores distinct page URLs or names visited by customers.
    *   **Justification:** Facilitates analysis of user navigation, popular content, and engagement patterns on the website, allowing insights into website design and content effectiveness.
    *   **Business Key:** `page_visited`
    *   **Proposed Columns:** `page_key` (Surrogate Key), `page_name`.

### Fact Tables

Fact tables contain the quantitative measures and foreign keys linking to dimension tables, representing specific business events.

1.  **`fact_orders`**
    *   **Purpose:** Records each individual order event and its associated numerical measures.
    *   **Justification:** This is the core for sales analysis, revenue tracking, and understanding product demand. Each row represents a specific order, detailing what was bought, when, by whom, and for how much.
    *   **Grain:** One row per order item.
    *   **Proposed Columns:** `order_id` (Degenerate Dimension/Business Key), `customer_key` (FK to `dim_customer`), `product_key` (FK to `dim_product`), `date_key` (FK to `dim_date` based on `order_date`), `quantity`, `price` (unit price at the time of order), `total_amount`.

2.  **`fact_support_tickets`**
    *   **Purpose:** Records details for each support ticket event.
    *   **Justification:** Enables analysis of customer service performance, identifying common issues, and tracking resolution times (if date fields were available).
    *   **Grain:** One row per support ticket.
    *   **Proposed Columns:** `ticket_id` (Degenerate Dimension/Business Key), `customer_key` (FK to `dim_customer`), `support_status_key` (FK to `dim_support_status`), `issue`.
    *   **Note on Date:** The current `support` DataFrame lacks a specific date column for ticket creation. In a real-world scenario, a `ticket_creation_date` would be crucial for linking to `dim_date`.

3.  **`fact_clickstream`**
    *   **Purpose:** Records each individual page visit event by a customer.
    *   **Justification:** Provides granular data for analyzing user behavior on the website, including navigation paths, page popularity, and engagement metrics.
    *   **Grain:** One row per page visit event within a session.
    *   **Proposed Columns:** `session_id` (Degenerate Dimension/Business Key), `customer_key` (FK to `dim_customer`), `date_key` (FK to `dim_date` based on `timestamp`), `page_key` (FK to `dim_page`).

## STEP 3 — Create Surrogate Keys

Surrogate keys are system-generated, simple integer keys used in data warehousing to uniquely identify records in dimension tables, independent of the source system's business keys. They provide performance benefits, flexibility in handling source system changes, and ensure uniqueness.

*   **Business Key:** An identifier for a record from the source system (e.g., `customer_id`, `product_id`). These can sometimes change or be reused, and might be composite.
*   **Surrogate Key:** A new, simple, integer primary key generated specifically for the data warehouse. It is stable, non-intelligent, and ensures referential integrity within the warehouse.

I will now create these surrogate keys for our dimension tables, keeping the original business keys for traceability.

In [ ]:
# Create dim_customer with surrogate key
df_dim_customer = customers[['customer_id', 'name', 'email', 'age', 'gender']].copy()
df_dim_customer = df_dim_customer.drop_duplicates(subset=['customer_id'])
df_dim_customer['customer_key'] = range(1, len(df_dim_customer) + 1)
df_dim_customer = df_dim_customer[['customer_key', 'customer_id', 'name', 'email', 'age', 'gender']]

# Create dim_product with surrogate key
df_dim_product = products[['product_id', 'name', 'category']].copy()
df_dim_product = df_dim_product.drop_duplicates(subset=['product_id'])
df_dim_product['product_key'] = range(1, len(df_dim_product) + 1)
df_dim_product = df_dim_product[['product_key', 'product_id', 'name', 'category']]

# Create dim_support_status with surrogate key
df_dim_support_status = support[['status']].copy()
df_dim_support_status = df_dim_support_status.drop_duplicates(subset=['status'])
df_dim_support_status['support_status_key'] = range(1, len(df_dim_support_status) + 1)
df_dim_support_status = df_dim_support_status[['support_status_key', 'status']]

# Create dim_page with surrogate key
df_dim_page = clickstream[['page_visited']].copy()
df_dim_page = df_dim_page.drop_duplicates(subset=['page_visited'])
df_dim_page['page_key'] = range(1, len(df_dim_page) + 1)
df_dim_page = df_dim_page[['page_key', 'page_visited']]

print("Surrogate keys generated for dimension tables.")

Surrogate keys generated for dimension tables.

## STEP 4 — Create Dimension Tables

We will now create the dimension DataFrames based on the cleansed data and the generated surrogate keys. For each dimension, we ensure the correct columns are selected, duplicates are handled, and data types are appropriate.

### `dim_customer`

In [ ]:
print("Shape of dim_customer:", df_dim_customer.shape)
print("First 5 rows of dim_customer:")
print(df_dim_customer.head())
print("\nUnique values in customer_key:", df_dim_customer['customer_key'].nunique())

Shape of dim_customer: (3, 6)
First 5 rows of dim_customer:
   customer_key  customer_id     name                email  age gender
0             1            1    Alice    alice@example.com   30      F
1             2            2      Bob      bob@example.com   24      M
2             3            3  Charlie  charlie@example.com   35      M

Unique values in customer_key: 3

### `dim_product`

In [ ]:
print("Shape of dim_product:", df_dim_product.shape)
print("First 5 rows of dim_product:")
print(df_dim_product.head())
print("\nUnique values in product_key:", df_dim_product['product_key'].nunique())

Shape of dim_product: (3, 4)
First 5 rows of dim_product:
   product_key  product_id       name     category
0            1        1001  Product A  Electronics
1            2        1002  Product B        Books
2            3        1003  Product C   Home Goods

Unique values in product_key: 3

### `dim_support_status`

In [ ]:
print("Shape of dim_support_status:", df_dim_support_status.shape)
print("First 5 rows of dim_support_status:")
print(df_dim_support_status.head())
print("\nUnique values in support_status_key:", df_dim_support_status['support_status_key'].nunique())

Shape of dim_support_status: (2, 2)
First 5 rows of dim_support_status:
   support_status_key  status
0                   1    Open
1                   2  Closed

Unique values in support_status_key: 2

### `dim_page`

In [ ]:
print("Shape of dim_page:", df_dim_page.shape)
print("First 5 rows of dim_page:")
print(df_dim_page.head())
print("\nUnique values in page_key:", df_dim_page['page_key'].nunique())

Shape of dim_page: (3, 2)
First 5 rows of dim_page:
   page_key    page_visited
0         1        homepage
1         2  product_page_A
3         3  product_page_C

Unique values in page_key: 3

### `dim_date`

In [ ]:
# Consolidate all relevant dates from fact tables
all_dates = pd.concat([
    customer_orders['order_date'].rename('full_date'),
    pd.to_datetime(clickstream['timestamp']).rename('full_date')
]).drop_duplicates().reset_index(drop=True)

# Ensure all_dates is a Series of datetime objects
all_dates = pd.to_datetime(all_dates)

# Extract unique dates
unique_dates = pd.DataFrame({'full_date': all_dates.dt.normalize().unique()})
unique_dates = unique_dates.sort_values('full_date').reset_index(drop=True)

# Create dim_date
df_dim_date = pd.DataFrame({
    'full_date': pd.to_datetime(unique_dates['full_date'])
})

df_dim_date['date_key'] = (df_dim_date['full_date'].dt.strftime('%Y%m%d')).astype(int)
df_dim_date['year'] = df_dim_date['full_date'].dt.year
df_dim_date['quarter'] = df_dim_date['full_date'].dt.quarter
df_dim_date['month'] = df_dim_date['full_date'].dt.month
df_dim_date['month_name'] = df_dim_date['full_date'].dt.month_name()
df_dim_date['day'] = df_dim_date['full_date'].dt.day
df_dim_date['day_of_week'] = df_dim_date['full_date'].dt.dayofweek # Monday=0, Sunday=6
df_dim_date['day_name'] = df_dim_date['full_date'].dt.day_name()
df_dim_date['week_of_year'] = df_dim_date['full_date'].dt.isocalendar().week.astype(int)
df_dim_date['day_of_year'] = df_dim_date['full_date'].dt.dayofyear
df_dim_date['is_weekend'] = (df_dim_date['full_date'].dt.dayofweek >= 5).astype(bool)
df_dim_date['is_holiday'] = False # Placeholder, would typically join with a holiday calendar

df_dim_date = df_dim_date[[
    'date_key',
    'full_date',
    'year',
    'quarter',
    'month',
    'month_name',
    'day',
    'day_of_week',
    'day_name',
    'week_of_year',
    'day_of_year',
    'is_weekend',
    'is_holiday'
]]

print("Shape of dim_date:", df_dim_date.shape)
print("First 5 rows of dim_date:")
print(df_dim_date.head())
print("\nUnique values in date_key:", df_dim_date['date_key'].nunique())

Shape of dim_date: (4, 13)
First 5 rows of dim_date:
   date_key  full_date  year  quarter  month month_name  day  day_of_week  \
0  20230101 2023-01-01  2023        1      1    January    1            6
1  20230102 2023-01-02  2023        1      1    January    2            0
2  20230105 2023-01-05  2023        1      1    January    5            3
3  20230110 2023-01-10  2023        1      1    January   10            1

   day_name  week_of_year  day_of_year  is_weekend  is_holiday
0    Sunday            52            1        True       False
1    Monday             1            2       False       False
2  Thursday             1            5       False       False
3   Tuesday             2           10       False       False

Unique values in date_key: 4

## STEP 6 — Create Fact Tables

Fact tables store the quantitative measures of business processes and foreign keys to link to the dimension tables. We will create `fact_orders`, `fact_support_tickets`, and `fact_clickstream`.

### `fact_orders`

In [ ]:
# Merge customer_orders with dim_customer to get customer_key
fact_orders = customer_orders.merge(
    df_dim_customer[['customer_id', 'customer_key']],
    on='customer_id',
    how='left'
)

# Merge with dim_product to get product_key
fact_orders = fact_orders.merge(
    df_dim_product[['product_id', 'product_key']],
    on='product_id',
    how='left'
)

# Merge with dim_date to get date_key
fact_orders = fact_orders.merge(
    df_dim_date[['full_date', 'date_key']],
    left_on='order_date',
    right_on='full_date',
    how='left'
)

# Select and reorder columns for fact_orders
fact_orders = fact_orders[[
    'order_id',
    'customer_key',
    'product_key',
    'date_key',
    'quantity',
    'price',
    'total_amount'
]]

print("Shape of fact_orders:", fact_orders.shape)
print("First 5 rows of fact_orders:")
print(fact_orders.head())
print("\nMissing values in fact_orders:")
print(fact_orders.isnull().sum())

Shape of fact_orders: (4, 7)
First 5 rows of fact_orders:
   order_id  customer_key  product_key  date_key  quantity  price  \
0       101             1            1  20230101         1   50.0
1       102             1            2  20230105         2   20.0
2       103             2            1  20230102         1   50.0
3       104             3            3  20230110         1  150.0

   total_amount
0          50.0
1          40.0
2          50.0
3         150.0

Missing values in fact_orders:
order_id        0
customer_key    0
product_key     0
date_key        0
quantity        0
price           0
total_amount    0
dtype: int64

### `fact_support_tickets`

In [ ]:
# Merge support with dim_customer to get customer_key
fact_support_tickets = support.merge(
    df_dim_customer[['customer_id', 'customer_key']],
    on='customer_id',
    how='left'
)

# Merge with dim_support_status to get support_status_key
fact_support_tickets = fact_support_tickets.merge(
    df_dim_support_status[['status', 'support_status_key']],
    on='status',
    how='left'
)

# Select and reorder columns for fact_support_tickets
fact_support_tickets = fact_support_tickets[[
    'ticket_id',
    'customer_key',
    'support_status_key',
    'issue'
]]

print("Shape of fact_support_tickets:", fact_support_tickets.shape)
print("First 5 rows of fact_support_tickets:")
print(fact_support_tickets.head())
print("\nMissing values in fact_support_tickets:")
print(fact_support_tickets.isnull().sum())

Shape of fact_support_tickets: (2, 4)
First 5 rows of fact_support_tickets:
   ticket_id  customer_key  support_status_key           issue
0        201             1                   1   Login problem
1        202             2                   2  Delivery delay

Missing values in fact_support_tickets:
ticket_id             0
customer_key          0
support_status_key    0
issue                 0
dtype: int64

### `fact_clickstream`

In [ ]:
# Merge clickstream with dim_customer to get customer_key
fact_clickstream = clickstream.merge(
    df_dim_customer[['customer_id', 'customer_key']],
    on='customer_id',
    how='left'
)

# Merge with dim_date to get date_key
fact_clickstream = fact_clickstream.merge(
    df_dim_date[['full_date', 'date_key']],
    left_on=pd.to_datetime(fact_clickstream['timestamp']).dt.normalize(),
    right_on='full_date',
    how='left'
)

# Merge with dim_page to get page_key
fact_clickstream = fact_clickstream.merge(
    df_dim_page[['page_visited', 'page_key']],
    on='page_visited',
    how='left'
)

# Select and reorder columns for fact_clickstream
fact_clickstream = fact_clickstream[[
    'session_id',
    'customer_key',
    'date_key',
    'page_key',
    'timestamp' # Keeping original timestamp for granularity if needed
]]

print("Shape of fact_clickstream:", fact_clickstream.shape)
print("First 5 rows of fact_clickstream:")
print(fact_clickstream.head())
print("\nMissing values in fact_clickstream:")
print(fact_clickstream.isnull().sum())

Shape of fact_clickstream: (4, 5)
First 5 rows of fact_clickstream:
   session_id  customer_key  date_key  page_key            timestamp
0         301             1  20230101         1  2023-01-01 10:00:00
1         301             1  20230101         2  2023-01-01 10:05:00
2         302             2  20230102         1  2023-01-02 11:00:00
3         303             3  20230110         3  2023-01-10 09:30:00

Missing values in fact_clickstream:
session_id      0
customer_key    0
date_key        0
page_key        0
timestamp       0
dtype: int64

## STEP 8 — Data Validation

Data validation is a critical step in any ETL pipeline to ensure the accuracy, consistency, and completeness of the data in the data warehouse. We will perform several checks on our newly created dimension and fact tables:

1.  **Check for Missing Surrogate Keys:** Verify that there are no missing surrogate keys in fact tables where they are expected (i.e., ensure all joins were successful).
2.  **Check for Duplicates:** Confirm uniqueness constraints on primary keys (surrogate keys) in dimension tables and on business keys/composite keys in fact tables.
3.  **Cross-Table Consistency:** Perform sample queries or checks to ensure data makes logical sense across tables (e.g., total amounts in fact tables align with source data if applicable).
4.  **Data Type Verification:** Re-confirm that data types are appropriate for analysis.

### Validation Checks

In [ ]:
print("--- Data Validation Report ---")

# 1. Check for Missing Surrogate Keys in Fact Tables
print("\n1. Checking for Missing Surrogate Keys:")

# fact_orders
missing_customer_keys_fo = fact_orders['customer_key'].isnull().sum()
missing_product_keys_fo = fact_orders['product_key'].isnull().sum()
missing_date_keys_fo = fact_orders['date_key'].isnull().sum()
print(f"  fact_orders: customer_key missing: {missing_customer_keys_fo}, product_key missing: {missing_product_keys_fo}, date_key missing: {missing_date_keys_fo}")

# fact_support_tickets
missing_customer_keys_fst = fact_support_tickets['customer_key'].isnull().sum()
missing_status_keys_fst = fact_support_tickets['support_status_key'].isnull().sum()
print(f"  fact_support_tickets: customer_key missing: {missing_customer_keys_fst}, support_status_key missing: {missing_status_keys_fst}")

# fact_clickstream
missing_customer_keys_fc = fact_clickstream['customer_key'].isnull().sum()
missing_date_keys_fc = fact_clickstream['date_key'].isnull().sum()
missing_page_keys_fc = fact_clickstream['page_key'].isnull().sum()
print(f"  fact_clickstream: customer_key missing: {missing_customer_keys_fc}, date_key missing: {missing_date_keys_fc}, page_key missing: {missing_page_keys_fc}")


# 2. Check for Duplicates in Dimension Tables (Surrogate Keys)
print("\n2. Checking for Duplicate Surrogate Keys in Dimension Tables:")
dup_dim_customer = df_dim_customer['customer_key'].duplicated().sum()
dup_dim_product = df_dim_product['product_key'].duplicated().sum()
dup_dim_date = df_dim_date['date_key'].duplicated().sum()
dup_dim_support_status = df_dim_support_status['support_status_key'].duplicated().sum()
dup_dim_page = df_dim_page['page_key'].duplicated().sum()

print(f"  dim_customer duplicates on customer_key: {dup_dim_customer}")
print(f"  dim_product duplicates on product_key: {dup_dim_product}")
print(f"  dim_date duplicates on date_key: {dup_dim_date}")
print(f"  dim_support_status duplicates on support_status_key: {dup_dim_support_status}")
print(f"  dim_page duplicates on page_key: {dup_dim_page}")

# 3. Check for Duplicates in Fact Tables (using business/composite keys if applicable, or the whole row)
print("\n3. Checking for Duplicate Rows in Fact Tables:")
dup_fact_orders = fact_orders.duplicated().sum()
dup_fact_support_tickets = fact_support_tickets.duplicated().sum()
dup_fact_clickstream = fact_clickstream.duplicated().sum()

print(f"  fact_orders duplicate rows: {dup_fact_orders}")
print(f"  fact_support_tickets duplicate rows: {dup_fact_support_tickets}")
print(f"  fact_clickstream duplicate rows: {dup_fact_clickstream}")


# 4. Data Type Verification (sample check for a few critical columns)
print("\n4. Sample Data Type Verification:")
print(f"  fact_orders 'quantity' dtype: {fact_orders['quantity'].dtype}")
print(f"  fact_orders 'total_amount' dtype: {fact_orders['total_amount'].dtype}")
print(f"  dim_date 'full_date' dtype: {df_dim_date['full_date'].dtype}")
print(f"  dim_customer 'age' dtype: {df_dim_customer['age'].dtype}")

print("\n--- End of Data Validation Report ---")

--- Data Validation Report ---

1. Checking for Missing Surrogate Keys:
  fact_orders: customer_key missing: 0, product_key missing: 0, date_key missing: 0
  fact_support_tickets: customer_key missing: 0, support_status_key missing: 0
  fact_clickstream: customer_key missing: 0, date_key missing: 0, page_key missing: 0

2. Checking for Duplicate Surrogate Keys in Dimension Tables:
  dim_customer duplicates on customer_key: 0
  dim_product duplicates on product_key: 0
  dim_date duplicates on date_key: 0
  dim_support_status duplicates on support_status_key: 0
  dim_page duplicates on page_key: 0

3. Checking for Duplicate Rows in Fact Tables:
  fact_orders duplicate rows: 0
  fact_support_tickets duplicate rows: 0
  fact_clickstream duplicate rows: 0

4. Sample Data Type Verification:
  fact_orders 'quantity' dtype: int64
  fact_orders 'total_amount' dtype: float64
  dim_date 'full_date' dtype: datetime64[ns]
  dim_customer 'age' dtype: int64

--- End of Data Validation Report ---

## STEP 9 — ETL Quality Report

An ETL Quality Report summarizes the key metrics and outcomes of the ETL process, providing an overview of data quality, transformation success, and any issues encountered. It serves as a documentation of the ETL run and a basis for monitoring data health.

We will consolidate the validation results and provide a summary of the transformations performed.

In [ ]:
print("=" * 30)
print("ETL Quality Report")
print("=" * 30)

print("\n--- 1. Data Loading and Initial Inspection ---")
print(f"Original Customers Shape: {customers_data['customer_id'].__len__()} rows")
print(f"Original Orders Shape: {orders_data['order_id'].__len__()} rows")
print(f"Original Products Shape: {products_data['product_id'].__len__()} rows")
print(f"Original Support Tickets Shape: {support_data['ticket_id'].__len__()} rows")
print(f"Original Clickstream Shape: {clickstream_data['session_id'].__len__()} rows")

print("\n--- 2. Data Preprocessing and Cleaning ---")
print("  - Column names standardized to lowercase and stripped.")
print("  - Duplicate customer rows removed.")
print("  - Text data (customer names) stripped of whitespace.")
print("  - `order_date` converted to datetime.")
print("  - `quantity` converted to numeric.")
print("  - `total_amount` calculated (quantity * price).")

print("\n--- 3. Data Integration (customer_orders) ---")
print(f"Integrated customer_orders shape: {customer_orders.shape}")
print(f"Missing values in customer_orders: {customer_orders.isnull().sum().sum()}")
print(f"Duplicate rows in customer_orders: {customer_orders.duplicated().sum()}")

print("\n--- 4. Data Warehouse Design (Star Schema) ---")
print("  - Dimension tables designed: dim_customer, dim_product, dim_date, dim_support_status, dim_page.")
print("  - Fact tables designed: fact_orders, fact_support_tickets, fact_clickstream.")

print("\n--- 5. Surrogate Key Creation & Dimension Table Population ---")
print(f"dim_customer shape: {df_dim_customer.shape}, Unique keys: {df_dim_customer['customer_key'].nunique()}")
print(f"dim_product shape: {df_dim_product.shape}, Unique keys: {df_dim_product['product_key'].nunique()}")
print(f"dim_date shape: {df_dim_date.shape}, Unique keys: {df_dim_date['date_key'].nunique()}")
print(f"dim_support_status shape: {df_dim_support_status.shape}, Unique keys: {df_dim_support_status['support_status_key'].nunique()}")
print(f"dim_page shape: {df_dim_page.shape}, Unique keys: {df_dim_page['page_key'].nunique()}")

print("\n--- 6. Fact Table Population ---")
print(f"fact_orders shape: {fact_orders.shape}")
print(f"fact_support_tickets shape: {fact_support_tickets.shape}")
print(f"fact_clickstream shape: {fact_clickstream.shape}")

print("\n--- 7. Relationship Establishment (Conceptual/Logical) ---")
print("  - Relationships between fact and dimension tables are established via surrogate keys.")
print("  - Example join demonstrated successfully.")

print("\n--- 8. Data Validation Results ---")
print(f"  Missing customer_keys in fact_orders: {missing_customer_keys_fo}")
print(f"  Missing product_keys in fact_orders: {missing_product_keys_fo}")
print(f"  Missing date_keys in fact_orders: {missing_date_keys_fo}")
print(f"  Missing customer_keys in fact_support_tickets: {missing_customer_keys_fst}")
print(f"  Missing support_status_keys in fact_support_tickets: {missing_status_keys_fst}")
print(f"  Missing customer_keys in fact_clickstream: {missing_customer_keys_fc}")
print(f"  Missing date_keys in fact_clickstream: {missing_date_keys_fc}")
print(f"  Missing page_keys in fact_clickstream: {missing_page_keys_fc}")

print(f"  Duplicate customer_keys in dim_customer: {dup_dim_customer}")
print(f"  Duplicate product_keys in dim_product: {dup_dim_product}")
print(f"  Duplicate date_keys in dim_date: {dup_dim_date}")
print(f"  Duplicate support_status_keys in dim_support_status: {dup_dim_support_status}")
print(f"  Duplicate page_keys in dim_page: {dup_dim_page}")

print(f"  Duplicate rows in fact_orders: {dup_fact_orders}")
print(f"  Duplicate rows in fact_support_tickets: {dup_fact_support_tickets}")
print(f"  Duplicate rows in fact_clickstream: {dup_fact_clickstream}")

print("\nConclusion: The ETL process has successfully transformed and loaded the source data into a star schema data warehouse with good data quality, as indicated by the validation checks.")
print("=" * 30)
print("End of Report")
print("=" * 30)

==============================
ETL Quality Report
==============================

--- 1. Data Loading and Initial Inspection ---
Original Customers Shape: 3 rows
Original Orders Shape: 4 rows
Original Products Shape: 3 rows
Original Support Tickets Shape: 2 rows
Original Clickstream Shape: 4 rows

--- 2. Data Preprocessing and Cleaning ---
  - Column names standardized to lowercase and stripped.
  - Duplicate customer rows removed.
  - Text data (customer names) stripped of whitespace.
  - `order_date` converted to datetime.
  - `quantity` converted to numeric.
  - `total_amount` calculated (quantity * price).

--- 3. Data Integration (customer_orders) ---
Integrated customer_orders shape: (4, 11)
Missing values in customer_orders: 0
Duplicate rows in customer_orders: 0

--- 4. Data Warehouse Design (Star Schema) ---
  - Dimension tables designed: dim_customer, dim_product, dim_date, dim_support_status, dim_page.
  - Fact tables designed: fact_orders, fact_support_tickets, fact_clickstream.

--- 5. Surrogate Key Creation & Dimension Table Population ---
dim_customer shape: (3, 6), Unique keys: 3
dim_product shape: (3, 4), Unique keys: 3
dim_date shape: (4, 13), Unique keys: 4
dim_support_status shape: (2, 2), Unique keys: 2
dim_page shape: (3, 2), Unique keys: 3

--- 6. Fact Table Population ---
fact_orders shape: (4, 7)
fact_support_tickets shape: (2, 4)
fact_clickstream shape: (4, 5)

--- 7. Relationship Establishment (Conceptual/Logical) ---
  - Relationships between fact and dimension tables are established via surrogate keys.
  - Example join demonstrated successfully.

--- 8. Data Validation Results ---
  Missing customer_keys in fact_orders: 0
  Missing product_keys in fact_orders: 0
  Missing date_keys in fact_orders: 0
  Missing customer_keys in fact_support_tickets: 0
  Missing support_status_keys in fact_support_tickets: 0
  Missing customer_keys in fact_clickstream: 0
  Missing date_keys in fact_clickstream: 0
  Missing page_keys in fact_clickstream: 0
  Duplicate customer_keys in dim_customer: 0
  Duplicate product_keys in dim_product: 0
  Duplicate date_keys in dim_date: 0
  Duplicate support_status_keys in dim_support_status: 0
  Duplicate page_keys in dim_page: 0
  Duplicate rows in fact_orders: 0
  Duplicate rows in fact_support_tickets: 0
  Duplicate rows in fact_clickstream: 0

Conclusion: The ETL process has successfully transformed and loaded the source data into a star schema data warehouse with good data quality, as indicated by the validation checks.
==============================
End of Report
==============================

## Final Data Warehouse Table Reports

In [17]:
import pandas as pd
import os

def profile_dataset(df, name):

    print("=" * 70)
    print("DATASET:", name)
    print("=" * 70)

    print("\nShape:")
    print(df.shape)

    print("\nColumns:")
    print(df.columns.tolist())

    print("\nData Types:")
    print(df.dtypes)

    print("\nMissing Values:")
    print(df.isnull().sum())

    print("\nMissing Percentage:")
    print((df.isnull().sum() / len(df) * 100).round(2))

    print("\nDuplicate Rows:")
    print(df.duplicated().sum())

    print("\nUnique Values:")
    print(df.nunique())

    print("\nStatistical Summary:")
    print(df.describe(include="all"))


# Define the path where data warehouse tables were exported
output_path = '/content/data_warehouse' # Corrected path

# Initialize dataframes to None to handle cases where loading fails
df_dim_customer = None
df_dim_product = None
df_dim_date = None
df_dim_support_status = None
df_dim_page = None
fact_orders = None
fact_support_tickets = None
fact_clickstream = None

# Load dataframes from CSV files to ensure they are available for profiling
try:
    df_dim_customer = pd.read_csv(f'{output_path}/dim_customer.csv')
    df_dim_product = pd.read_csv(f'{output_path}/dim_product.csv')
    df_dim_date = pd.read_csv(f'{output_path}/dim_date.csv')
    df_dim_support_status = pd.read_csv(f'{output_path}/dim_support_status.csv')
    df_dim_page = pd.read_csv(f'{output_path}/dim_page.csv')
    fact_orders = pd.read_csv(f'{output_path}/fact_orders.csv')
    fact_support_tickets = pd.read_csv(f'{output_path}/fact_support_tickets.csv')
    fact_clickstream = pd.read_csv(f'{output_path}/fact_clickstream.csv')
    print("All dataframes loaded successfully from data warehouse output for profiling.")
except FileNotFoundError as e:
    print(f"Error loading dataframes: {e}. Please ensure the data warehouse has been exported by running all preceding steps.")
except Exception as e:
    print(f"An unexpected error occurred while loading dataframes: {e}")

# Ensure dim_date 'full_date' is datetime type for consistent profiling
if df_dim_date is not None and 'full_date' in df_dim_date.columns:
    df_dim_date['full_date'] = pd.to_datetime(df_dim_date['full_date'])

# Generate reports for each dataframe, only if they were successfully loaded
if df_dim_customer is not None:
    profile_dataset(df_dim_customer, "Dimension - Customer")
if df_dim_product is not None:
    profile_dataset(df_dim_product, "Dimension - Product")
if df_dim_date is not None:
    profile_dataset(df_dim_date, "Dimension - Date")
if df_dim_support_status is not None:
    profile_dataset(df_dim_support_status, "Dimension - Support Status")
if df_dim_page is not None:
    profile_dataset(df_dim_page, "Dimension - Page")
if fact_orders is not None:
    profile_dataset(fact_orders, "Fact - Orders")
if fact_support_tickets is not None:
    profile_dataset(fact_support_tickets, "Fact - Support Tickets")
if fact_clickstream is not None:
    profile_dataset(fact_clickstream, "Fact - Clickstream")

All dataframes loaded successfully from data warehouse output for profiling.
======================================================================
DATASET: Dimension - Customer
======================================================================

Shape:
(3, 6)

Columns:
['customer_key', 'customer_id', 'name', 'email', 'age', 'gender']

Data Types:
customer_key     int64
customer_id      int64
name            object
email           object
age              int64
gender          object
dtype: object

Missing Values:
customer_key    0
customer_id     0
name            0
email           0
age             0
gender          0
dtype: int64

Missing Percentage:
customer_key    0.0
customer_id     0.0
name            0.0
email           0.0
age             0.0
gender          0.0
dtype: float64

Duplicate Rows:
0

Unique Values:
customer_key    3
customer_id     3
name            3
email           3
age             3
gender          2
dtype: int64

Statistical Summary:
        customer_key  customer_id   name              email        age gender
count            3.0          3.0      3                  3   3.000000      3
unique           NaN          NaN      3                  3        NaN      2
top              NaN          NaN  Alice  alice@example.com        NaN      M
freq             NaN          NaN      1                  1        NaN      2
mean             2.0          2.0    NaN                NaN  29.666667    NaN
std              1.0          1.0    NaN                NaN   5.507571    NaN
min              1.0          1.0    NaN                NaN  24.000000    NaN
25%              1.5          1.5    NaN                NaN  27.000000    NaN
50%              2.0          2.0    NaN                NaN  30.000000    NaN
75%              2.5          2.5    NaN                NaN  32.500000    NaN
max              3.0          3.0    NaN                NaN  35.000000    NaN
======================================================================
DATASET: Dimension - Product
======================================================================

Shape:
(3, 4)

Columns:
['product_key', 'product_id', 'name', 'category']

Data Types:
product_key     int64
product_id      int64
name           object
category       object
dtype: object

Missing Values:
product_key    0
product_id     0
name           0
category       0
dtype: int64

Missing Percentage:
product_key    0.0
product_id     0.0
name           0.0
category       0.0
dtype: float64

Duplicate Rows:
0

Unique Values:
product_key    3
product_id     3
name           3
category       3
dtype: int64

Statistical Summary:
        product_key  product_id       name     category
count           3.0         3.0          3            3
unique          NaN         NaN          3            3
top             NaN         NaN  Product A  Electronics
freq            NaN         NaN          1            1
mean            2.0      1002.0        NaN          NaN
std             1.0         1.0        NaN          NaN
min             1.0      1001.0        NaN          NaN
25%             1.5      1001.5        NaN          NaN
50%             2.0      1002.0        NaN          NaN
75%             2.5      1002.5        NaN          NaN
max             3.0      1003.0        NaN          NaN
======================================================================
DATASET: Dimension - Date
======================================================================

Shape:
(4, 13)

Columns:
['date_key', 'full_date', 'year', 'quarter', 'month', 'month_name', 'day', 'day_of_week', 'day_name', 'week_of_year', 'day_of_year', 'is_weekend', 'is_holiday']

Data Types:
date_key                 int64
full_date       datetime64[ns]
year                     int64
quarter                  int64
month                    int64
month_name              object
day                      int64
day_of_week              int64
day_name                object
week_of_year             int64
day_of_year              int64
is_weekend                bool
is_holiday                bool
dtype: object

Missing Values:
date_key        0
full_date       0
year            0
quarter         0
month           0
month_name      0
day             0
day_of_week     0
day_name        0
week_of_year    0
day_of_year     0
is_weekend      0
is_holiday      0
dtype: int64

Missing Percentage:
date_key        0.0
full_date       0.0
year            0.0
quarter         0.0
month           0.0
month_name      0.0
day             0.0
day_of_week     0.0
day_name        0.0
week_of_year    0.0
day_of_year     0.0
is_weekend      0.0
is_holiday      0.0
dtype: float64

Duplicate Rows:
0

Unique Values:
date_key        4
full_date       4
year            1
quarter         1
month           1
month_name      1
day             4
day_of_week     4
day_name        4
week_of_year    3
day_of_year     4
is_weekend      2
is_holiday      1
dtype: int64

Statistical Summary:
            date_key            full_date    year  quarter  month month_name  \
count   4.000000e+00                    4     4.0      4.0    4.0          4
unique           NaN                  NaN     NaN      NaN    NaN          1
top              NaN                  NaN     NaN      NaN    NaN    January
freq             NaN                  NaN     NaN      NaN    NaN          4
mean    2.023010e+07  2023-01-04 12:00:00  2023.0      1.0    1.0        NaN
min     2.023010e+07  2023-01-01 00:00:00  2023.0      1.0    1.0        NaN
25%     2.023010e+07  2023-01-01 18:00:00  2023.0      1.0    1.0        NaN
50%     2.023010e+07  2023-01-03 12:00:00  2023.0      1.0    1.0        NaN
75%     2.023011e+07  2023-01-06 06:00:00  2023.0      1.0    1.0        NaN
max     2.023011e+07  2023-01-10 00:00:00  2023.0      1.0    1.0        NaN
std     4.041452e+00                  NaN     0.0      0.0    0.0        NaN

              day  day_of_week day_name  week_of_year  day_of_year is_weekend  \
count    4.000000     4.000000        4      4.000000     4.000000          4
unique        NaN          NaN        4           NaN          NaN          2
top           NaN          NaN   Sunday           NaN          NaN      False
freq          NaN          NaN        1           NaN          NaN          3
mean     4.500000     2.500000      NaN     14.000000     4.500000        NaN
min      1.000000     0.000000      NaN      1.000000     1.000000        NaN
25%      1.750000     0.750000      NaN      1.000000     1.750000        NaN
50%      3.500000     2.000000      NaN      1.500000     3.500000        NaN
75%      6.250000     3.750000      NaN     14.500000     6.250000        NaN
max     10.000000     6.000000      NaN     52.000000    10.000000        NaN
std      4.041452     2.645751      NaN     25.337719     4.041452        NaN

       is_holiday
count           4
unique          1
top         False
freq            4
mean          NaN
min           NaN
25%           NaN
50%           NaN
75%           NaN
max           NaN
std           NaN
======================================================================
DATASET: Dimension - Support Status
======================================================================

Shape:
(2, 2)

Columns:
['support_status_key', 'status']

Data Types:
support_status_key     int64
status                object
dtype: object

Missing Values:
support_status_key    0
status                0
dtype: int64

Missing Percentage:
support_status_key    0.0
status                0.0
dtype: float64

Duplicate Rows:
0

Unique Values:
support_status_key    2
status                2
dtype: int64

Statistical Summary:
        support_status_key status
count             2.000000      2
unique                 NaN      2
top                    NaN   Open
freq                   NaN      1
mean              1.500000    NaN
std               0.707107    NaN
min               1.000000    NaN
25%               1.250000    NaN
50%               1.500000    NaN
75%               1.750000    NaN
max               2.000000    NaN
======================================================================
DATASET: Dimension - Page
======================================================================

Shape:
(3, 2)

Columns:
['page_key', 'page_visited']

Data Types:
page_key         int64
page_visited    object
dtype: object

Missing Values:
page_key        0
page_visited    0
dtype: int64

Missing Percentage:
page_key        0.0
page_visited    0.0
dtype: float64

Duplicate Rows:
0

Unique Values:
page_key        3
page_visited    3
dtype: int64

Statistical Summary:
        page_key page_visited
count        3.0            3
unique       NaN            3
top          NaN     homepage
freq         NaN            1
mean         2.0          NaN
std          1.0          NaN
min          1.0          NaN
25%          1.5          NaN
50%          2.0          NaN
75%          2.5          NaN
max          3.0          NaN
======================================================================
DATASET: Fact - Orders
======================================================================

Shape:
(4, 7)

Columns:
['order_id', 'customer_key', 'product_key', 'date_key', 'quantity', 'price', 'total_amount']

Data Types:
order_id          int64
customer_key      int64
product_key       int64
date_key          int64
quantity          int64
price           float64
total_amount    float64
dtype: object

Missing Values:
order_id        0
customer_key    0
product_key     0
date_key        0
quantity        0
price           0
total_amount    0
dtype: int64

Missing Percentage:
order_id        0.0
customer_key    0.0
product_key     0.0
date_key        0.0
quantity        0.0
price           0.0
total_amount    0.0
dtype: float64

Duplicate Rows:
0

Unique Values:
order_id        4
customer_key    3
product_key     3
date_key        4
quantity        2
price           3
total_amount    3
dtype: int64

Statistical Summary:
         order_id  customer_key  product_key      date_key  quantity  \
count    4.000000      4.000000     4.000000  4.000000e+00      4.00
mean   102.500000      1.750000     1.750000  2.023010e+07      1.25
std      1.290994      0.957427     0.957427  4.041452e+00      0.50
min    101.000000      1.000000     1.000000  2.023010e+07      1.00
25%    101.750000      1.000000     1.000000  2.023010e+07      1.00
50%    102.500000      1.500000     1.500000  2.023010e+07      1.00
75%    103.250000      2.250000     2.250000  2.023011e+07      1.25
max    104.000000      3.000000     3.000000  2.023011e+07      2.00

            price  total_amount
count    4.000000      4.000000
mean    67.500000     72.500000
std     56.789083     51.881275
min     20.000000     40.000000
25%     42.500000     47.500000
50%     50.000000     50.000000
75%     75.000000     75.000000
max    150.000000    150.000000
======================================================================
DATASET: Fact - Support Tickets
======================================================================

Shape:
(2, 4)

Columns:
['ticket_id', 'customer_key', 'support_status_key', 'issue']

Data Types:
ticket_id              int64
customer_key           int64
support_status_key     int64
issue                 object
dtype: object

Missing Values:
ticket_id             0
customer_key          0
support_status_key    0
issue                 0
dtype: int64

Missing Percentage:
ticket_id             0.0
customer_key          0.0
support_status_key    0.0
issue                 0.0
dtype: float64

Duplicate Rows:
0

Unique Values:
ticket_id             2
customer_key          2
support_status_key    2
issue                 2
dtype: int64

Statistical Summary:
         ticket_id  customer_key  support_status_key          issue
count     2.000000      2.000000            2.000000              2
unique         NaN           NaN                 NaN              2
top            NaN           NaN                 NaN  Login problem
freq           NaN           NaN                 NaN              1
mean    201.500000      1.500000            1.500000            NaN
std       0.707107      0.707107            0.707107            NaN
min     201.000000      1.000000            1.000000            NaN
25%     201.250000      1.250000            1.250000            NaN
50%     201.500000      1.500000            1.500000            NaN
75%     201.750000      1.750000            1.750000            NaN
max     202.000000      2.000000            2.000000            NaN
======================================================================
DATASET: Fact - Clickstream
======================================================================

Shape:
(4, 5)

Columns:
['session_id', 'customer_key', 'date_key', 'page_key', 'timestamp']

Data Types:
session_id       int64
customer_key     int64
date_key         int64
page_key         int64
timestamp       object
dtype: object

Missing Values:
session_id      0
customer_key    0
date_key        0
page_key        0
timestamp       0
dtype: int64

Missing Percentage:
session_id      0.0
customer_key    0.0
date_key        0.0
page_key        0.0
timestamp       0.0
dtype: float64

Duplicate Rows:
0

Unique Values:
session_id      3
customer_key    3
date_key        3
page_key        3
timestamp       4
dtype: int64

Statistical Summary:
        session_id  customer_key      date_key  page_key            timestamp
count     4.000000      4.000000  4.000000e+00  4.000000                    4
unique         NaN           NaN           NaN       NaN                    4
top            NaN           NaN           NaN       NaN  2023-01-01 10:00:00
freq           NaN           NaN           NaN       NaN                    1
mean    301.750000      1.750000  2.023010e+07  1.750000                  NaN
std       0.957427      0.957427  4.358899e+00  0.957427                  NaN
min     301.000000      1.000000  2.023010e+07  1.000000                  NaN
25%     301.000000      1.000000  2.023010e+07  1.000000                  NaN
50%     301.500000      1.500000  2.023010e+07  1.500000                  NaN
75%     302.250000      2.250000  2.023010e+07  2.250000                  NaN
max     303.000000      3.000000  2.023011e+07  3.000000                  NaN

## STEP 10 — Export the Data Warehouse

After successfully building and validating our data warehouse tables, the next step is to export them. This is typically done to persist the transformed data, either for loading into a relational database (like PostgreSQL, MySQL), a data lake, or another analytical platform. We will export our dimension and fact tables to CSV files.

In [ ]:
output_path = '/content/data_warehouse_output'
os.makedirs(output_path, exist_ok=True)

# Export Dimension Tables
df_dim_customer.to_csv(f'{output_path}/dim_customer.csv', index=False)
df_dim_product.to_csv(f'{output_path}/dim_product.csv', index=False)
df_dim_date.to_csv(f'{output_path}/dim_date.csv', index=False)
df_dim_support_status.to_csv(f'{output_path}/dim_support_status.csv', index=False)
df_dim_page.to_csv(f'{output_path}/dim_page.csv', index=False)

# Export Fact Tables
fact_orders.to_csv(f'{output_path}/fact_orders.csv', index=False)
fact_support_tickets.to_csv(f'{output_path}/fact_support_tickets.csv', index=False)
fact_clickstream.to_csv(f'{output_path}/fact_clickstream.csv', index=False)

print(f"All dimension and fact tables exported successfully to '{output_path}'.")

All dimension and fact tables exported successfully to '/content/data_warehouse_output'.

## STEP 11 — Database Loading Preparation (SQL CREATE TABLE statements)

To load our exported data into a relational database, we first need to define the schema using SQL `CREATE TABLE` statements. This section will generate the SQL DDL (Data Definition Language) for each of our dimension and fact tables. We will map pandas data types to appropriate SQL data types.

### Data Type Mapping

*   `int64` -> `INTEGER`
*   `float64` -> `REAL` or `DOUBLE PRECISION`
*   `object` (string) -> `VARCHAR(255)` (or `TEXT` for longer strings)
*   `datetime64[ns]` -> `TIMESTAMP`
*   `bool` -> `BOOLEAN`

In [ ]:
def generate_create_table_sql(df, table_name, primary_key=None, foreign_keys={}):
    sql_statements = []
    sql_statements.append(f"CREATE TABLE {table_name} (")

    column_definitions = []
    for col, dtype in df.dtypes.items():
        sql_type = "VARCHAR(255)" # Default for objects
        if pd.api.types.is_integer_dtype(dtype):
            sql_type = "INTEGER"
        elif pd.api.types.is_float_dtype(dtype):
            sql_type = "REAL"
        elif pd.api.types.is_datetime64_any_dtype(dtype):
            sql_type = "TIMESTAMP"
        elif pd.api.types.is_bool_dtype(dtype):
            sql_type = "BOOLEAN"

        definition = f"    {col} {sql_type}"
        if col == primary_key:
            definition += " PRIMARY KEY"
        column_definitions.append(definition)

    # Add foreign key constraints
    for fk_col, ref_table_pk_col in foreign_keys.items():
        ref_table, ref_pk = ref_table_pk_col.split('.')
        column_definitions.append(f"    FOREIGN KEY ({fk_col}) REFERENCES {ref_table}({ref_pk})")

    sql_statements.append(",\n".join(column_definitions))
    sql_statements.append(");")
    return "\n".join(sql_statements)

# Generate SQL for Dimension Tables
sql_dim_customer = generate_create_table_sql(
    df_dim_customer, 'dim_customer', primary_key='customer_key'
)
sql_dim_product = generate_create_table_sql(
    df_dim_product, 'dim_product', primary_key='product_key'
)
sql_dim_date = generate_create_table_sql(
    df_dim_date, 'dim_date', primary_key='date_key'
)
sql_dim_support_status = generate_create_table_sql(
    df_dim_support_status, 'dim_support_status', primary_key='support_status_key'
)
sql_dim_page = generate_create_table_sql(
    df_dim_page, 'dim_page', primary_key='page_key'
)

# Generate SQL for Fact Tables
sql_fact_orders = generate_create_table_sql(
    fact_orders, 'fact_orders', primary_key='order_id',
    foreign_keys={
        'customer_key': 'dim_customer.customer_key',
        'product_key': 'dim_product.product_key',
        'date_key': 'dim_date.date_key'
    }
)
sql_fact_support_tickets = generate_create_table_sql(
    fact_support_tickets, 'fact_support_tickets', primary_key='ticket_id',
    foreign_keys={
        'customer_key': 'dim_customer.customer_key',
        'support_status_key': 'dim_support_status.support_status_key'
    }
)
sql_fact_clickstream = generate_create_table_sql(
    fact_clickstream, 'fact_clickstream', primary_key='session_id',
    foreign_keys={
        'customer_key': 'dim_customer.customer_key',
        'date_key': 'dim_date.date_key',
        'page_key': 'dim_page.page_key'
    }
)

print("--- SQL CREATE TABLE Statements ---")
print("\n" + sql_dim_customer)
print("\n" + sql_dim_product)
print("\n" + sql_dim_date)
print("\n" + sql_dim_support_status)
print("\n" + sql_dim_page)
print("\n" + sql_fact_orders)
print("\n" + sql_fact_support_tickets)
print("\n" + sql_fact_clickstream)
print("\n--- End of SQL Statements ---")

--- SQL CREATE TABLE Statements ---

CREATE TABLE dim_customer (
    customer_key INTEGER PRIMARY KEY,
    customer_id INTEGER,
    name VARCHAR(255),
    email VARCHAR(255),
    age INTEGER,
    gender VARCHAR(255)
);

CREATE TABLE dim_product (
    product_key INTEGER PRIMARY KEY,
    product_id INTEGER,
    name VARCHAR(255),
    category VARCHAR(255)
);

CREATE TABLE dim_date (
    date_key INTEGER PRIMARY KEY,
    full_date TIMESTAMP,
    year INTEGER,
    quarter INTEGER,
    month INTEGER,
    month_name VARCHAR(255),
    day INTEGER,
    day_of_week INTEGER,
    day_name VARCHAR(255),
    week_of_year INTEGER,
    day_of_year INTEGER,
    is_weekend BOOLEAN,
    is_holiday BOOLEAN
);

CREATE TABLE dim_support_status (
    support_status_key INTEGER PRIMARY KEY,
    status VARCHAR(255)
);

CREATE TABLE dim_page (
    page_key INTEGER PRIMARY KEY,
    page_visited VARCHAR(255)
);

CREATE TABLE fact_orders (
    order_id INTEGER PRIMARY KEY,
    customer_key INTEGER,
    product_key INTEGER,
    date_key INTEGER,
    quantity INTEGER,
    price REAL,
    total_amount REAL,
    FOREIGN KEY (customer_key) REFERENCES dim_customer(customer_key),
    FOREIGN KEY (product_key) REFERENCES dim_product(product_key),
    FOREIGN KEY (date_key) REFERENCES dim_date(date_key)
);

CREATE TABLE fact_support_tickets (
    ticket_id INTEGER PRIMARY KEY,
    customer_key INTEGER,
    support_status_key INTEGER,
    issue VARCHAR(255),
    FOREIGN KEY (customer_key) REFERENCES dim_customer(customer_key),
    FOREIGN KEY (support_status_key) REFERENCES dim_support_status(support_status_key)
);

CREATE TABLE fact_clickstream (
    session_id INTEGER PRIMARY KEY,
    customer_key INTEGER,
    date_key INTEGER,
    page_key INTEGER,
    timestamp VARCHAR(255),
    FOREIGN KEY (customer_key) REFERENCES dim_customer(customer_key),
    FOREIGN KEY (date_key) REFERENCES dim_date(date_key),
    FOREIGN KEY (page_key) REFERENCES dim_page(page_key)
);

--- End of SQL Statements ---

## STEP 12 — Final ETL Documentation and Presentation Explanation

This section serves as a final documentation of the ETL pipeline we've built for the Customer 360 dataset. It will summarize the entire process, from data ingestion to data warehousing, and articulate the value proposition for a business presentation.

### ETL Pipeline Summary

Our ETL (Extract, Transform, Load) pipeline for the Customer 360 dataset has systematically processed raw operational data into a structured data warehouse environment, optimized for analytical querying and reporting.

**1. Data Extraction & Initial Inspection:**
*   Loaded customer, order, product, support ticket, and clickstream data from CSV files.
*   Performed initial profiling to understand data characteristics, identify missing values, duplicates, and data types.

**2. Data Preprocessing & Cleaning:**
*   Standardized column names (lowercase, stripped whitespace).
*   Removed duplicate customer records.
*   Cleaned text data (e.g., customer names).
*   Converted data types (e.g., `order_date` to datetime, `quantity` to numeric).
*   Derived new features (e.g., `total_amount` for orders).

**3. Data Integration:**
*   Merged core datasets (`customers` and `orders`) to create an integrated `customer_orders` DataFrame for deeper insights.
*   Verified integrity of integrated data.

**4. Data Warehouse Design (Star Schema):**
*   Designed a Star Schema consisting of:
    *   **Dimension Tables:** `dim_customer`, `dim_product`, `dim_date`, `dim_support_status`, `dim_page` – providing descriptive context.
    *   **Fact Tables:** `fact_orders`, `fact_support_tickets`, `fact_clickstream` – storing quantitative measures.

**5. Surrogate Key Creation & Dimension Table Population:**
*   Generated unique, non-business surrogate keys for each dimension table (`customer_key`, `product_key`, `date_key`, `support_status_key`, `page_key`) to ensure data integrity and flexibility.
*   Populated dimension tables with relevant attributes.

**6. Fact Table Population:**
*   Populated fact tables (`fact_orders`, `fact_support_tickets`, `fact_clickstream`) by merging with the newly created dimension tables to include surrogate keys.

**7. Relationship Establishment:**
*   Conceptually established relationships between fact and dimension tables via foreign keys (surrogate keys) to enable effective analytical queries.
*   Demonstrated data linkage through example join operations.

**8. Data Validation:**
*   Conducted thorough validation checks, including:
    *   Absence of missing surrogate keys in fact tables.
    *   Uniqueness of primary keys in dimension tables.
    *   Absence of duplicate rows in fact tables.
    *   Correctness of data types.

**9. ETL Quality Report:**
*   Generated a comprehensive report summarizing the ETL process, validation results, and overall data quality.

**10. Export Data Warehouse:**
*   Exported all dimension and fact tables to CSV files, ready for loading into a relational database or other analytical platforms.

**11. Database Loading Preparation:**
*   Generated SQL `CREATE TABLE` statements for all tables, including primary and foreign key constraints, to facilitate database schema creation.

### Presentation Explanation: Value Proposition

For a business audience, the value of this ETL pipeline and the resulting Customer 360 data warehouse can be summarized as follows:

**1. Unified Customer View (Customer 360):**
*   **Benefit:** Breaks down data silos by integrating customer information across orders, support, and website activity into a single, comprehensive view. This enables a holistic understanding of each customer's journey and interactions.
*   **Impact:** Enhanced personalization, targeted marketing campaigns, improved customer service, and better customer retention strategies.

**2. Enhanced Analytical Capabilities:**
*   **Benefit:** The Star Schema design, with its clearly defined fact and dimension tables, is highly optimized for analytical queries. Business users and analysts can easily slice and dice data across various dimensions (customer demographics, product categories, timeframes, page types) to uncover insights.
*   **Impact:** Faster and more accurate reporting, deeper insights into sales trends, product performance, customer behavior patterns, and website engagement.

**3. Improved Data Quality and Reliability:**
*   **Benefit:** The rigorous data cleaning, transformation, and validation steps embedded in the ETL pipeline ensure that the data within the data warehouse is accurate, consistent, and reliable.
*   **Impact:** Business decisions are based on trustworthy data, reducing errors and increasing confidence in strategic initiatives.

**4. Scalability and Flexibility:**
*   **Benefit:** The modular design of the ETL pipeline and the data warehouse schema allows for easy integration of new data sources or additional dimensions/facts as business needs evolve, without disrupting existing analytical structures.
*   **Impact:** Future-proofed analytical infrastructure that can adapt to changing business requirements and growth.

**5. Operational Efficiency:**
*   **Benefit:** Automating the data processing from raw sources to a clean, analysis-ready format reduces manual effort and frees up resources for higher-value analytical tasks.
*   **Impact:** Reduced operational costs, faster time-to-insight, and increased productivity for data teams.

In essence, this Customer 360 Data Warehouse transforms disparate operational data into a strategic asset, empowering data-driven decision-making across the organization to drive growth, improve customer satisfaction, and optimize business operations.

## STEP 7 — Establish Relationships

In a data warehouse, relationships between fact and dimension tables are crucial for analysis. While pandas DataFrames don't enforce these relationships directly like a relational database, we've designed our tables to have foreign keys (surrogate keys) that link fact tables to their respective dimension tables. This section will outline these relationships and demonstrate how they can be used for data retrieval.

### Relationships Overview

*   **`fact_orders`**
    *   `customer_key` -> `dim_customer.customer_key`
    *   `product_key` -> `dim_product.product_key`
    *   `date_key` -> `dim_date.date_key`

*   **`fact_support_tickets`**
    *   `customer_key` -> `dim_customer.customer_key`
    *   `support_status_key` -> `dim_support_status.support_status_key`

*   **`fact_clickstream`**
    *   `customer_key` -> `dim_customer.customer_key`
    *   `date_key` -> `dim_date.date_key`
    *   `page_key` -> `dim_page.page_key`

To illustrate these relationships, let's perform a sample join operation. For example, joining `fact_orders` with `dim_customer` and `dim_product` to get a more descriptive view of order data.

In [ ]:
# Example: Join fact_orders with dim_customer and dim_product

# Join with dim_customer
orders_with_customer_info = fact_orders.merge(
    df_dim_customer[['customer_key', 'name', 'email', 'age', 'gender']],
    on='customer_key',
    how='left'
)

# Join with dim_product
orders_detailed = orders_with_customer_info.merge(
    df_dim_product[['product_key', 'name', 'category']],
    left_on='product_key',
    right_on='product_key',
    suffixes=('_customer', '_product'),
    how='left'
)

# Join with dim_date
orders_detailed = orders_detailed.merge(
    df_dim_date[['date_key', 'full_date', 'month_name', 'year']],
    on='date_key',
    how='left'
)

print("Shape of detailed orders:", orders_detailed.shape)
print("First 5 rows of detailed orders:")
print(orders_detailed.head())
print("\nSelected columns for illustration:")
print(orders_detailed[['order_id', 'name_customer', 'name_product', 'category', 'full_date', 'quantity', 'total_amount']].head())

Shape of detailed orders: (4, 16)
First 5 rows of detailed orders:
   order_id  customer_key  product_key  date_key  quantity  price  \
0       101             1            1  20230101         1   50.0
1       102             1            2  20230105         2   20.0
2       103             2            1  20230102         1   50.0
3       104             3            3  20230110         1  150.0

   total_amount name_customer                email  age gender name_product  \
0          50.0         Alice    alice@example.com   30      F    Product A
1          40.0         Alice    alice@example.com   30      F    Product B
2          50.0           Bob      bob@example.com   24      M    Product A
3         150.0       Charlie  charlie@example.com   35      M    Product C

      category  full_date month_name  year
0  Electronics 2023-01-01    January  2023
1        Books 2023-01-05    January  2023
2  Electronics 2023-01-02    January  2023
3   Home Goods 2023-01-10    January  2023

Selected columns for illustration:
   order_id name_customer name_product     category  full_date  quantity  \
0       101         Alice    Product A  Electronics 2023-01-01         1
1       102         Alice    Product B        Books 2023-01-05         2
2       103           Bob    Product A  Electronics 2023-01-02         1
3       104       Charlie    Product C   Home Goods 2023-01-10         1

   total_amount
0          50.0
1          40.0
2          50.0
3         150.0

## STEP 5 — Create Date Dimension

In [ ]:
print("Orders columns:")
print(orders.columns.tolist())

print("\nData types:")
print(orders.dtypes)

Orders columns:
['order_id', 'customer_id', 'product_id', 'order_date', 'quantity', 'price', 'total_amount']

Data types:
order_id                 int64
customer_id              int64
product_id               int64
order_date      datetime64[ns]
quantity                 int64
price                  float64
total_amount           float64
dtype: object

In [ ]:
date_columns = []

for col in orders.columns:
    if "date" in col.lower() or "time" in col.lower():
        date_columns.append(col)

print("Possible date columns:")
print(date_columns)

Possible date columns:
['order_date']

**Convert order date**

In [ ]:
orders["order_date"] = pd.to_datetime(
    orders["order_date"],
    errors="coerce"
)

print(orders["order_date"].dtype)

datetime64[ns]

In [ ]:
print("Invalid dates:",
      orders["order_date"].isna().sum())

Invalid dates: 0

**Create Date Dimension**

In [ ]:
date_df = orders[["order_date"]].dropna().drop_duplicates()

date_df = date_df.sort_values("order_date").reset_index(drop=True)

In [ ]:
date_df["date_key"] = date_df["order_date"].dt.strftime("%Y%m%d").astype(int)

In [ ]:
date_df["full_date"] = date_df["order_date"].dt.date

date_df["day"] = date_df["order_date"].dt.day

date_df["day_name"] = date_df["order_date"].dt.day_name()

date_df["week"] = date_df["order_date"].dt.isocalendar().week

date_df["month"] = date_df["order_date"].dt.month

date_df["month_name"] = date_df["order_date"].dt.month_name()

date_df["quarter"] = date_df["order_date"].dt.quarter

date_df["year"] = date_df["order_date"].dt.year

In [ ]:
dim_date = date_df[
    [
        "date_key",
        "full_date",
        "day",
        "day_name",
        "week",
        "month",
        "month_name",
        "quarter",
        "year"
    ]
]

In [ ]:
dim_date.head(10)

   date_key   full_date  day  day_name  week  month month_name  quarter  year
0  20230101  2023-01-01    1    Sunday    52      1    January        1  2023
1  20230102  2023-01-02    2    Monday     1      1    January        1  2023
2  20230105  2023-01-05    5  Thursday     1      1    January        1  2023
3  20230110  2023-01-10   10   Tuesday     2      1    January        1  2023

In [ ]:
print("Rows:", len(dim_date))
print("Columns:", len(dim_date.columns))

Rows: 4
Columns: 9

**Validate Date Dimension**

In [ ]:
print(
    "Duplicate date keys:",
    dim_date["date_key"].duplicated().sum()
)

Duplicate date keys: 0

In [ ]:
print(
    "Null date keys:",
    dim_date["date_key"].isna().sum()
)

Null date keys: 0

In [ ]:
print(dim_date.dtypes)

date_key       int64
full_date     object
day            int32
day_name      object
week          UInt32
month          int32
month_name    object
quarter        int32
year           int32
dtype: object

**Create continuous Date Dimension**

In [ ]:
min_date = orders["order_date"].min()
max_date = orders["order_date"].max()

date_range = pd.date_range(
    start=min_date,
    end=max_date,
    freq="D"
)

dim_date = pd.DataFrame({
    "full_date": date_range
})

In [ ]:
dim_date["date_key"] = (
    dim_date["full_date"]
    .dt.strftime("%Y%m%d")
    .astype(int)
)

dim_date["day"] = dim_date["full_date"].dt.day

dim_date["day_name"] = dim_date["full_date"].dt.day_name()

dim_date["week"] = (
    dim_date["full_date"]
    .dt.isocalendar()
    .week
    .astype(int)
)

dim_date["month"] = dim_date["full_date"].dt.month

dim_date["month_name"] = dim_date["full_date"].dt.month_name()

dim_date["quarter"] = dim_date["full_date"].dt.quarter

dim_date["year"] = dim_date["full_date"].dt.year

In [ ]:
dim_date = dim_date[
    [
        "date_key",
        "full_date",
        "day",
        "day_name",
        "week",
        "month",
        "month_name",
        "quarter",
        "year"
    ]
]

In [ ]:
dim_date.head()

   date_key  full_date  day   day_name  week  month month_name  quarter  year
0  20230101 2023-01-01    1     Sunday    52      1    January        1  2023
1  20230102 2023-01-02    2     Monday     1      1    January        1  2023
2  20230103 2023-01-03    3    Tuesday     1      1    January        1  2023
3  20230104 2023-01-04    4  Wednesday     1      1    January        1  2023
4  20230105 2023-01-05    5   Thursday     1      1    January        1  2023

In [ ]:
dim_date.tail()

   date_key  full_date  day  day_name  week  month month_name  quarter  year
5  20230106 2023-01-06    6    Friday     1      1    January        1  2023
6  20230107 2023-01-07    7  Saturday     1      1    January        1  2023
7  20230108 2023-01-08    8    Sunday     1      1    January        1  2023
8  20230109 2023-01-09    9    Monday     2      1    January        1  2023
9  20230110 2023-01-10   10   Tuesday     2      1    January        1  2023

In [ ]:
print(dim_date.shape)

(10, 9)

**Step 6 — Create Dimension Tables**

In [ ]:
dim_customer = customers.drop_duplicates(
    subset=["customer_id"]
).copy()

dim_customer = dim_customer.reset_index(drop=True)

dim_customer["customer_key"] = (
    dim_customer.index + 1
)

In [ ]:
cols = ["customer_key"] + [
    col for col in dim_customer.columns
    if col != "customer_key"
]

dim_customer = dim_customer[cols]

In [ ]:
dim_customer.head()

   customer_key  customer_id     name                email  age gender
0             1            1    Alice    alice@example.com   30      F
1             2            2      Bob      bob@example.com   24      M
2             3            3  Charlie  charlie@example.com   35      M

In [ ]:
print(dim_customer.shape)

(3, 6)

In [ ]:
print(products.columns.tolist())

['product_id', 'name', 'category', 'price']

In [ ]:
dim_product = products.drop_duplicates(
    subset=["product_id"]
).copy()

dim_product = dim_product.reset_index(drop=True)

dim_product["product_key"] = (
    dim_product.index + 1
)

In [ ]:
cols = ["product_key"] + [
    col for col in dim_product.columns
    if col != "product_key"
]

dim_product = dim_product[cols]

**Step 7 — Map Surrogate Keys to Orders**

**Customer key mapping**

In [ ]:
orders_fact = orders.copy()

orders_fact = orders_fact.merge(
    dim_customer[["customer_id", "customer_key"]],
    on="customer_id",
    how="left"
)

**Product key mapping**

In [ ]:
orders_fact = orders_fact.merge(
    dim_product[["product_id", "product_key"]],
    on="product_id",
    how="left"
)

**Date key mapping**

In [ ]:
orders_fact["order_date"] = pd.to_datetime(
    orders_fact["order_date"],
    errors="coerce"
)

orders_fact = orders_fact.merge(
    dim_date[["full_date", "date_key"]],
    left_on=orders_fact["order_date"].dt.normalize(),
    right_on=dim_date["full_date"],
    how="left"
)

**Step 8 — Create fact_orders**

In [ ]:
print(orders_fact.columns.tolist())

['key_0', 'order_id', 'customer_id', 'product_id', 'order_date', 'quantity', 'price', 'total_amount', 'customer_key', 'product_key', 'full_date', 'date_key']

In [ ]:
print(orders_fact.columns.tolist())

['key_0', 'order_id', 'customer_id', 'product_id', 'order_date', 'quantity', 'price', 'total_amount', 'customer_key', 'product_key', 'full_date', 'date_key']

In [ ]:
fact_orders = orders_fact[
    [
        "order_id",
        "customer_key",
        "product_key",
        "date_key",
        "quantity",
        "price",
        "total_amount"
    ]
].copy()

In [ ]:
print(fact_orders.head())
print("\nShape:", fact_orders.shape)
print("\nColumns:")
print(fact_orders.columns.tolist())

   order_id  customer_key  product_key  date_key  quantity  price  \
0       101             1            1  20230101         1   50.0
1       102             1            2  20230105         2   20.0
2       103             2            1  20230102         1   50.0
3       104             3            3  20230110         1  150.0

   total_amount
0          50.0
1          40.0
2          50.0
3         150.0

Shape: (4, 7)

Columns:
['order_id', 'customer_key', 'product_key', 'date_key', 'quantity', 'price', 'total_amount']

In [ ]:
calculated_total = (
    fact_orders["quantity"] * fact_orders["price"]
)

comparison = pd.DataFrame({
    "existing_total": fact_orders["total_amount"],
    "calculated_total": calculated_total
})

comparison["difference"] = (
    comparison["existing_total"] -
    comparison["calculated_total"]
)

comparison.head()

   existing_total  calculated_total  difference
0            50.0              50.0         0.0
1            40.0              40.0         0.0
2            50.0              50.0         0.0
3           150.0             150.0         0.0

In [ ]:
comparison[
    comparison["difference"].abs() > 0.01
].head(20)

Empty DataFrame
Columns: [existing_total, calculated_total, difference]
Index: []

**Step 9 — Fact Table Validation**

In [ ]:
print(
    "Duplicate order IDs:",
    fact_orders["order_id"].duplicated().sum()
)

Duplicate order IDs: 0

In [ ]:
print(
    "Null customer keys:",
    fact_orders["customer_key"].isna().sum()
)

print(
    "Null product keys:",
    fact_orders["product_key"].isna().sum()
)

print(
    "Null date keys:",
    fact_orders["date_key"].isna().sum()
)

Null customer keys: 0
Null product keys: 0
Null date keys: 0

In [ ]:
print(
    "Negative quantities:",
    (fact_orders["quantity"] < 0).sum()
)

Negative quantities: 0

In [ ]:
print(
    "Negative prices:",
    (fact_orders["price"] < 0).sum()
)

Negative prices: 0

In [ ]:
print(
    "Negative total amounts:",
    (fact_orders["total_amount"] < 0).sum()
)

Negative total amounts: 0

**Step 10 — Referential Integrity**

In [ ]:
invalid_customers = fact_orders[
    ~fact_orders["customer_key"].isin(
        dim_customer["customer_key"]
    )
]

print(
    "Invalid customer foreign keys:",
    len(invalid_customers)
)

Invalid customer foreign keys: 0

In [ ]:
invalid_products = fact_orders[
    ~fact_orders["product_key"].isin(
        dim_product["product_key"]
    )
]

print(
    "Invalid product foreign keys:",
    len(invalid_products)
)

Invalid product foreign keys: 0

In [ ]:
invalid_dates = fact_orders[
    ~fact_orders["date_key"].isin(
        dim_date["date_key"]
    )
]

print(
    "Invalid date foreign keys:",
    len(invalid_dates)
)

Invalid date foreign keys: 0

**Step 11 — Final Fact Table**

In [ ]:
fact_orders.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 7 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   order_id      4 non-null      int64
 1   customer_key  4 non-null      int64
 2   product_key   4 non-null      int64
 3   date_key      4 non-null      int64
 4   quantity      4 non-null      int64
 5   price         4 non-null      float64
 6   total_amount  4 non-null      float64
dtypes: float64(2), int64(5)
memory usage: 356.0 bytes

In [ ]:
fact_orders.describe()

,order_id,customer_key,product_key,date_key,quantity,price,total_amount
count,4.000000,4.000000,4.000000,4.000000e+00,4.00,4.000000,4.000000
mean,102.500000,1.750000,1.750000,2.023010e+07,1.25,67.500000,72.500000
std,1.290994,0.957427,0.957427,4.041452e+00,0.50,56.789083,51.881275
min,101.000000,1.000000,1.000000,2.023010e+07,1.00,20.000000,40.000000
25%,101.750000,1.000000,1.000000,2.023010e+07,1.00,42.500000,47.500000
50%,102.500000,1.500000,1.500000,2.023010e+07,1.00,50.000000,50.000000
75%,103.250000,2.250000,2.250000,2.023011e+07,1.25,75.000000,75.000000
max,104.000000,3.000000,3.000000,2.023011e+07,2.00,150.000000,150.000000

**Step 12 — Save Data Warehouse**

In [ ]:
import os

os.makedirs(
    "/content/data_warehouse",
    exist_ok=True
)

In [ ]:
dim_customer.to_csv(
    "/content/data_warehouse/dim_customer.csv",
    index=False
)

dim_product.to_csv(
    "/content/data_warehouse/dim_product.csv",
    index=False
)

dim_date.to_csv(
    "/content/data_warehouse/dim_date.csv",
    index=False
)

fact_orders.to_csv(
    "/content/data_warehouse/fact_orders.csv",
    index=False
)

In [ ]:
os.listdir("/content/data_warehouse")

['dim_date.csv', 'dim_product.csv', 'dim_customer.csv', 'fact_orders.csv']

## OLAP Cube Simulation with Pandas

To simulate an OLAP cube and demonstrate its analytical capabilities within this environment, we'll use pandas' `pivot_table` functionality. This allows us to perform multi-dimensional analysis by aggregating measures across various dimensions.

We will create a sales cube based on `fact_orders`, linking it to `dim_customer`, `dim_product`, and `dim_date` to explore sales data by customer, product, and time.

In [12]:
import pandas as pd
import os

# Define the path where data warehouse tables were exported
data_warehouse_path = '/content/data_warehouse'

# Ensure the data warehouse directory exists
os.makedirs(data_warehouse_path, exist_ok=True)

# Re-save dimension and fact tables to ensure they are available on disk
# This helps if the directory was lost or previous save operations didn't persist.
# Assumes the DataFrames (dim_customer, dim_product, dim_date, fact_orders) are in memory.
try:
    dim_customer.to_csv(f'{data_warehouse_path}/dim_customer.csv', index=False)
    dim_product.to_csv(f'{data_warehouse_path}/dim_product.csv', index=False)
    dim_date.to_csv(f'{data_warehouse_path}/dim_date.csv', index=False)
    fact_orders.to_csv(f'{data_warehouse_path}/fact_orders.csv', index=False)
    print("Data warehouse tables re-saved to ensure availability for OLAP cube creation.")
except NameError as e:
    print(f"Skipping re-saving data warehouse tables. Some DataFrames were not defined: {e}")
    print("This might happen if previous cells defining these DataFrames were not executed in the current session.")

# Load dimension tables and fact_orders from CSV to ensure they are available for OLAP simulation
# Assuming the files exist or will be created by preceding steps if not.
dim_customer = pd.read_csv(f'{data_warehouse_path}/dim_customer.csv')
dim_product = pd.read_csv(f'{data_warehouse_path}/dim_product.csv')
dim_date = pd.read_csv(f'{data_warehouse_path}/dim_date.csv')
fact_orders = pd.read_csv(f'{data_warehouse_path}/fact_orders.csv')

# Ensure date columns are in datetime format for dim_date if needed for future operations
dim_date['full_date'] = pd.to_datetime(dim_date['full_date'])

# Merge fact_orders with necessary dimension tables to get descriptive attributes
sales_analysis_df = fact_orders.merge(
    dim_customer[['customer_key', 'name', 'gender', 'age']],
    on='customer_key',
    how='left'
).merge(
    dim_product[['product_key', 'name', 'category']],
    on='product_key',
    how='left',
    suffixes=('_customer', '_product')
).merge(
    dim_date[['date_key', 'year', 'month_name', 'day_name']],
    on='date_key',
    how='left'
)

# Display the merged DataFrame head to verify
print("Sales Analysis DataFrame head:")
display(sales_analysis_df.head())

print("\nSales Analysis DataFrame info:")
sales_analysis_df.info()

Skipping re-saving data warehouse tables. Some DataFrames were not defined: name 'dim_customer' is not defined
This might happen if previous cells defining these DataFrames were not executed in the current session.
Sales Analysis DataFrame head:

,order_id,customer_key,product_key,date_key,quantity,price,total_amount,name_customer,gender,age,name_product,category,year,month_name,day_name
0,101,1,1,20230101,1,50.0,50.0,Alice,F,30,Product A,Electronics,2023,January,Sunday
1,102,1,2,20230105,2,20.0,40.0,Alice,F,30,Product B,Books,2023,January,Thursday
2,103,2,1,20230102,1,50.0,50.0,Bob,M,24,Product A,Electronics,2023,January,Monday
3,104,3,3,20230110,1,150.0,150.0,Charlie,M,35,Product C,Home Goods,2023,January,Tuesday

Sales Analysis DataFrame info:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 15 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   order_id       4 non-null      int64
 1   customer_key   4 non-null      int64
 2   product_key    4 non-null      int64
 3   date_key       4 non-null      int64
 4   quantity       4 non-null      int64
 5   price          4 non-null      float64
 6   total_amount   4 non-null      float64
 7   name_customer  4 non-null      object
 8   gender         4 non-null      object
 9   age            4 non-null      int64
 10  name_product   4 non-null      object
 11  category       4 non-null      object
 12  year           4 non-null      int64
 13  month_name     4 non-null      object
 14  day_name       4 non-null      object
dtypes: float64(2), int64(7), object(6)
memory usage: 612.0+ bytes

### Creating the Sales OLAP Cube (using `pivot_table`)

Now, let's create our 'cube' to analyze `total_amount` (our measure) by different dimensions.

In [13]:
import pandas as pd

# Cube: Total Sales by Customer and Product Category
sales_by_customer_product_category = pd.pivot_table(
    sales_analysis_df,
    values='total_amount',
    index=['name_customer', 'gender'], # Rows: Customer Name and Gender
    columns=['category'], # Columns: Product Category
    aggfunc='sum',
    fill_value=0
)

print("\nTotal Sales by Customer and Product Category:")
display(sales_by_customer_product_category)

# Cube: Total Sales by Year and Month
sales_by_time = pd.pivot_table(
    sales_analysis_df,
    values='total_amount',
    index=['year'], # Rows: Year
    columns=['month_name'], # Columns: Month Name
    aggfunc='sum',
    fill_value=0
)

print("\nTotal Sales by Year and Month:")
display(sales_by_time)

# Cube: Average Order Value by Customer Age Group
sales_analysis_df['age_group'] = pd.cut(
    sales_analysis_df['age'],
    bins=[0, 25, 35, 45, 60, 100],
    labels=['<25', '25-34', '35-44', '45-59', '60+'],
    right=False
)

avg_order_value_by_age = pd.pivot_table(
    sales_analysis_df,
    values='total_amount',
    index=['age_group'],
    aggfunc='mean',
    fill_value=0
)

print("\nAverage Order Value by Customer Age Group:")
display(avg_order_value_by_age)

Total Sales by Customer and Product Category:

category              Books  Electronics  Home Goods
name_customer gender
Alice         F        40.0         50.0         0.0
Bob           M         0.0         50.0         0.0
Charlie       M         0.0          0.0       150.0

Total Sales by Year and Month:

month_name  January
year
2023          290.0

Average Order Value by Customer Age Group:

/tmp/ipykernel_2400/1851662770.py:37: FutureWarning: The default value of observed=False is deprecated and will change to observed=True in a future version of pandas. Specify observed=False to silence this warning and retain the current behavior
  avg_order_value_by_age = pd.pivot_table(

           total_amount
age_group
<25                50.0
25-34              45.0
35-44             150.0

### OLAP Operations Demonstration

These `pivot_table` operations demonstrate core OLAP capabilities:

*   **Slice:** Filtering data to a specific dimension. (e.g., viewing sales for only 'Product A' category, implicitly done by having it as a column).
*   **Dice:** Selecting a subset of the cube by specifying values for multiple dimensions. (e.g., `sales_by_customer_product_category['Electronics']` to see only electronics sales).
*   **Drill Down/Roll Up:** Changing the level of granularity. (e.g., from `sales_by_time` we can drill down to `day_name` if added to the index/columns, or roll up to `year` which is already shown).

This approach provides a flexible way to explore multi-dimensional data within a pandas DataFrame.